export enum ActionType {
  FETCH_ARTICLES = 'FETCH_ARTICLES',
  FETCH_ARTICLES_SUCCESS = 'FETCH_ARTICLES_SUCCESS',
  FETCH_ARTICLES_ERROR = 'FETCH_ARTICLES_ERROR',
  FETCH_COMMENT = 'FETCH_COMMENT',
  FETCH_COMMENT_SUCCESS = 'FETCH_COMMENT_SUCCESS',
  FETCH_COMMENT_ERROR = 'FETCH_COMMENT_ERROR',
  ADD_COMMENT_TO_FAVOURITE = 'ADD_COMMENT_TO_FAVOURITE',
  DELETE_COMMENT_FROM_FAVOURITE = 'DELETE_COMMENT_FROM_FAVOURITE',
  ADD_POST_TO_FAVOURITE = 'ADD_POST_TO_FAVOURITE',
}
